### ISSUE TITLE
Sublime 2 support is broken

### ISSUE THREAD

**Issue by printercu** [ddiachkov/sublime-yaml-nav#11]
Package doesnt work with sublime 2 after https://github.com/ddiachkov/sublime-yaml-nav/commit/06276bec70fdb537e8cee197d44df252c2f7c004 
http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html says that `.sublime-syntax` is available only in dev channel.

Is it possible/hard to keep sublime 2 support?

**Comment by AlexanderZaytsev** [comment]
Same issue. Quick tip if you want to make it work on Sublime 2:
* Download .zip from here: https://github.com/ddiachkov/sublime-yaml-nav/tree/v1.3.1
* In Sublime, go to Preferences -> Browse Packages. Find the `YAML Nav` folder there. Replace its contents with that of the .zip file.
