### ISSUE TITLE
Last symbol being trimmed

### ISSUE THREAD

**Issue by piotrgo** [ddiachkov/sublime-yaml-nav#7]
Hello,

I am using this plugin on Yosemite, with ST3. On the status bar every last symbol is being trimmed down,
on copying (or jumping to the key), it's the last one that's being trimmed down.

For example:
test:
  key-number: one

On copy I would get "test.key-numbe"

It only happens with keys that have "-" in it, so next example would be:

test-two:
  key: two

output would be "test-tw.key"

Cheers,
Piotr

**Comment by Jonnymcc** [comment]
This is still an issue in version 1.3.1.
