### ISSUE TITLE
Last character being trimmed from keys containg hyphens

### ISSUE THREAD

**Issue by Jonnymcc** [ddiachkov/sublime-yaml-nav#8]
Issue #7 still exists in version 1.3.1 on Ubuntu 14.04. Happens when jumping to or copying a symbol.

Example:
```
test-key:
  test:
    another-test: test
```
will appear as `test-ke.test.another-tes`

**Comment by ddiachkov** [comment]
Which mode do you use: "YAML" or "YAML (YAML Nav)"?
(it's written in the right bottom corner of Sublime's window)

**Comment by Jonnymcc** [comment]
I usually use "YAML" but have the same issue in "YAML (YAML Nav)". Is using the " "YAML (YAML Nav)" mode a necessity?

**Comment by ddiachkov** [comment]
Yeah, there is a bug in vanilla YAML syntax definition.
You can try this: run command "Set syntax: YAML (YAML Nav)", change file (type a space for example) and then copy symbol. Should work correctly.

**Comment by Jonnymcc** [comment]
Yup that worked. Is there an open issue to fix the default YAML syntax definition in ST3?

**Comment by ddiachkov** [comment]
No, there is not. I'll open an issue since John is back.
Also I'll try to force "YAML (YAML Nav)" by default for YAML files.

**Comment by xelldran1** [comment]
Happens on OS X 10.10 with sublime text 3 build 3083 using both YAML and YAML Nav syntaxes.

**Comment by Grokzen** [comment]
Still happens on Ubuntu 14.04 with ST3 build 3095 with both syntaxes

**Comment by allaire** [comment]
Still happens with latest beta on OS X, your workaround fixed it!

**Comment by Sheval** [comment]
And it still exists in version 1.3.1 on Ubuntu 14.04 with ST3 build 3103 with both syntaxes

**Comment by phillipoertel** [comment]
I get the same problem with both syntaxes in Rails i18n files ("e.dat.format.shor"). 
In database.yml I don't get it, however, no matter which YAML syntax I use.

Let me know if I can help debugging; your package would help me a lot but I can't use it at the moment.

I'm on OS X with Sublime Text build 3103.

**Comment by phillipoertel** [comment]
I can get it to work even with the Rails i18n files if I fiddle with it long enough. The YAML array syntax (see screenshot) may have to do something with it. When I remove those keys, as well as the three dashes at the beginning of the file, sometimes the strings look correct. Sometimes not. 
I think the list of keys isn't rebuilt on every change, that's why changing the file doesn't have a deterministic effect on the menu.
Is there a way to change the package so that it rebuilds the list on every change of the file? That would make debugging a lot easier.

![bildschirmfoto 2016-03-09 um 23 39 25](https://cloud.githubusercontent.com/assets/5188/13653136/30929fe8-e650-11e5-8516-0ff0ce4c8e6f.png)

**Comment by phillipoertel** [comment]
Here's a screenshot. Unfortunately I have no reliable way of producing this ...

![bildschirmfoto 2016-03-09 um 23 49 04](https://cloud.githubusercontent.com/assets/5188/13653371/9f1795bc-e651-11e5-937b-8806c585beea.png)

**Comment by ddiachkov** [comment]
Ok, I am back in business.

> Is there a way to change the package so that it rebuilds the list on every change of the file

Actually it already do it. List will be automatically rebuilt after 0.4s from the last buffer change.

**Comment by ddiachkov** [comment]
I just released version 1.3.2 with brand new YAML syntax from https://github.com/sublimehq/Packages/pull/90. It should fix the problem.

**Comment by phillipoertel** [comment]
It works now. You rock!
One more thing (not essential though, I think): when the YAML keys are symbols, the symbols are also shown in the selection dropdown, where they wouldn't be necessary; compare screenshot.

![bildschirmfoto 2016-03-13 um 11 06 18](https://cloud.githubusercontent.com/assets/5188/13728083/cce89a6a-e90b-11e5-8944-f7a38958d241.png)

**Comment by ddiachkov** [comment]
Implemented in 1.4.0
